In [1]:
import torch

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
x = torch.arange(1,12)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
x.shape

torch.Size([11])

In [7]:
x.numel()

11

In [9]:
x = torch.arange(12)
x2 = x.reshape(3,4)
x2

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [11]:
x2.shape, x2.numel()

(torch.Size([3, 4]), 12)

In [17]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
torch.zeros_like(x)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
torch.ones_like(x2)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [15]:
torch.rand(3,4)

tensor([[0.1445, 0.2013, 0.7065, 0.6267],
        [0.5662, 0.3875, 0.9703, 0.8516],
        [0.8170, 0.3494, 0.1504, 0.6716]])

In [16]:
torch.rand((3,4))

tensor([[0.2649, 0.9612, 0.2802, 0.9013],
        [0.1353, 0.7583, 0.8753, 0.5486],
        [0.4921, 0.5922, 0.4981, 0.9233]])

In [18]:
torch.rand((3,))

tensor([0.9631, 0.8905, 0.4587])

In [21]:
torch.rand((1,3))

tensor([[0.7808, 0.5057, 0.5127]])

In [24]:
x = torch.tensor([1, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x+y, x-y, x*y,x/y,x**y

(tensor([ 3,  4,  6, 10]),
 tensor([-1,  0,  2,  6]),
 tensor([ 2,  4,  8, 16]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1,  4, 16, 64]))

In [40]:
torch.exp2(torch.tensor(4.0))

tensor(16.)

In [36]:
x = torch.arange(12, dtype=torch.float32).reshape(3,4)
y = x
torch.cat((x,y), dim = 0), torch.cat((x,y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  1.,  2.,  3.,  0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.,  4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.,  8.,  9., 10., 11.]]))

In [37]:
x == y

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [38]:
x.sum(), x.mean(), x.median(), x.var()

(tensor(66.), tensor(5.5000), tensor(5.), tensor(13.))

In [42]:
torch.arange(3).reshape(3,1), torch.arange(3).reshape((3,1))

(tensor([[0],
         [1],
         [2]]),
 tensor([[0],
         [1],
         [2]]))

In [46]:
torch.arange(3).reshape(3,1)+torch.arange(1,3).reshape(1,2)

tensor([[1, 2],
        [2, 3],
        [3, 4]])

In [47]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [48]:
x[-1], x[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [56]:
x[1:2,:2], x[1,3]

(tensor([[4., 5.]]), tensor(7.))

In [58]:
x[1:2]=12
x

tensor([[ 0.,  1.,  2.,  3.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [64]:
x = torch.tensor([1.0, 2, 3, 4])
y = torch.rand_like(x)
before = id(y)
y = y + x
id(y) == before

False

In [62]:
x = torch.tensor([1.0, 2, 3, 4])
y = torch.rand_like(x)
before = id(y)
y[:] = y + x
id(y) == before

True

In [66]:
x = torch.tensor([1.0, 2, 3, 4])
y = torch.rand_like(x)
before = id(y)
y += x
id(y) == before

True

In [67]:
A = x.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [69]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [70]:
x < y

tensor([True, True, True, True])

In [71]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([2., 3., 4., 5.], device='cuda:0')
tensor([2., 3., 4., 5.], dtype=torch.float64)
