In [1]:
import torch

In [2]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x+y, x*y, x/y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [3]:
x = torch.arange(4)
x, x[3], len(x), x.shape

(tensor([0, 1, 2, 3]), tensor(3), 4, torch.Size([4]))

In [4]:
A = torch.arange(16,dtype=torch.float32).reshape(4,4)
A, A.T, A.inverse()

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]]),
 tensor([[ 0.,  4.,  8., 12.],
         [ 1.,  5.,  9., 13.],
         [ 2.,  6., 10., 14.],
         [ 3.,  7., 11., 15.]]),
 tensor([[ -1398101.3750,         0.0000,   4194304.0000,  -2796202.7500],
         [  5592405.0000,  -8388608.0000,         0.0000,   2796202.7500],
         [ -6990507.0000,  16777216.0000, -12582912.0000,   2796202.5000],
         [  2796203.5000,  -8388608.0000,   8388608.0000,  -2796202.7500]]))

In [5]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [6]:
A = torch.arange(20, dtype = torch.float32).reshape(5,4)
B = A.clone()
id(A) == id(B), A, A+B

(False,
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [7]:
A*B, torch.multiply(A,B),torch.mul(A,B)

(tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.],
         [144., 169., 196., 225.],
         [256., 289., 324., 361.]]),
 tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.],
         [144., 169., 196., 225.],
         [256., 289., 324., 361.]]),
 tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.],
         [144., 169., 196., 225.],
         [256., 289., 324., 361.]]))

In [8]:
torch.matmul(A,B.T)

tensor([[  14.,   38.,   62.,   86.,  110.],
        [  38.,  126.,  214.,  302.,  390.],
        [  62.,  214.,  366.,  518.,  670.],
        [  86.,  302.,  518.,  734.,  950.],
        [ 110.,  390.,  670.,  950., 1230.]])

In [9]:
x = torch.arange(4, dtype = torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [10]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

In [11]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis1 = A.sum(axis=1)
A, A_sum_axis0, A_sum_axis0.shape, A_sum_axis1, A_sum_axis1.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([40., 45., 50., 55.]),
 torch.Size([4]),
 tensor([ 6., 22., 38., 54., 70.]),
 torch.Size([5]))

In [12]:
A.sum(axis=[0,1])

tensor(190.)

In [13]:
A.mean(axis=1), A.numel()

(tensor([ 1.5000,  5.5000,  9.5000, 13.5000, 17.5000]), 20)

In [14]:
A.mean(axis = 0), A.sum(axis=0)/A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [15]:
A.sum(axis=1, keepdims = True), A.sum(axis=1, keepdims = False)

(tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 tensor([ 6., 22., 38., 54., 70.]))

In [16]:
A, A.cumsum(axis=0)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  6.,  8., 10.],
         [12., 15., 18., 21.],
         [24., 28., 32., 36.],
         [40., 45., 50., 55.]]))

In [17]:
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [18]:
torch.sum(x*y)

tensor(6.)

In [19]:
A.shape, x.shape, torch.mv(A,x), torch.matmul(A,x)

(torch.Size([5, 4]),
 torch.Size([4]),
 tensor([ 14.,  38.,  62.,  86., 110.]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

In [20]:
B = torch.ones(4,3)
torch.mm(A,B), torch.matmul(A,B)

(tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

In [21]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [22]:
torch.abs(u).sum()

tensor(7.)

In [23]:
torch.ones(4,9)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
torch.norm(torch.ones(4,9))

tensor(6.)

In [25]:
A = torch.tensor([[1, 0, 0],[0, 4, 0],[0, 0, 9]], dtype=torch.float32)
A

tensor([[1., 0., 0.],
        [0., 4., 0.],
        [0., 0., 9.]])

In [26]:
eigenvlues, eigenvectors = A.eig(eigenvectors=True)
eigenvlues, eigenvectors

(tensor([[1., 0.],
         [4., 0.],
         [9., 0.]]),
 tensor([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]))

In [27]:
A = torch.arange(20, dtype = torch.float32).reshape(5,4)
A, A/A.sum(axis=0), A.sum(axis=0)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]]),
 tensor([40., 45., 50., 55.]))