In [1]:
import torch
from torch import nn
from torch.nn import functional as F

In [2]:
x = torch.arange(4)
torch.save(x, 'x-file')
x

tensor([0, 1, 2, 3])

In [3]:
x2 = torch.load('x-file')
x2

tensor([0, 1, 2, 3])

In [4]:
y = torch.zeros(4)
torch.save([x, y], 'x-files')
x2, y2 = torch.load('x-files')
x2, y2

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [5]:
mydict = {'x':x, 'y':y}
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [6]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)
    
    def forward(self, X):
        return self.output(self.hidden(X))

In [7]:
net = MLP()
X = torch.randn((2, 20))
Y = net(X)
print(X, Y)
net.eval()

tensor([[-0.4131,  0.0552, -0.8184,  0.1276, -0.7768,  1.8102, -0.5524, -0.8978,
         -2.0028,  0.0867, -0.8802, -1.5651,  1.0910,  0.9283, -0.1704,  0.5837,
         -1.4026,  1.3273, -1.9397,  0.9542],
        [ 0.3374, -0.8663, -0.2772,  0.4478, -0.9935,  0.9714,  0.5104, -0.0977,
         -1.4228, -0.3741, -0.7325, -0.5829, -0.0315, -1.5467, -0.2496,  1.7411,
         -0.1411, -1.2666, -0.0314,  1.0505]]) tensor([[-0.2528, -0.1431, -0.3268, -0.1007, -0.3072, -0.1535,  0.3572, -0.3715,
          0.0882,  0.1310],
        [-0.0032, -0.1740, -0.0043,  0.1399,  0.3302, -0.1632,  0.6536,  0.9401,
          0.2604, -0.2082]], grad_fn=<AddmmBackward>)


MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [8]:
torch.save(net.state_dict(), 'mlp.params')

In [9]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [10]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])